version: "3.8"
volumes:
  php-fpm-socket:
  db-store:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./laravel:/work/backend
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
      - MAIL_HOST=mail
      - MAIL_PORT=1025
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./laravel:/work/backend

  db:
    build:
      context: .
      dockerfile: ./infra/postgresql/Dockerfile
      args:
        - DB_USER=${DB_USER:-phper}
        - DB_NAME=${DB_NAME:-laravel_local}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-laravel_local}
      - POSTGRES_USER=${DB_USER:-phper}
      - POSTGRES_PASSWORD=${DB_PASS:-secret}
      - POSTGRES_ROOT_PASSWORD=${DB_PASS:-secret}

  mail:
    build:
      context: .
      dockerfile: ./infra/mailhog/Dockerfile
    ports:
      - ${MAIL_PORT}:8025